/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.CuentaCON;
import java.util.Date;
import javax.swing.JTextField;
import com.toedter.calendar.JDateChooser;
import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gauge
 */
public class Login extends javax.swing.JFrame {
 
   
   
    String run;
    ImageIcon iconoOriginal;
  
    public Login() {
      
        
        initComponents();
        this.setLocationRelativeTo(this);
        SetImageLabel(fondo, "src/imagenes/fondo.png");
        SetImageLabel(icono, "src/imagenes/icono.png");
        this.iconoOriginal = (ImageIcon) RegistrarseL.getIcon();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

 
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        cemail = new javax.swing.JTextField();
        Botonsiguiente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ccontrasena = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        RegistrarseL = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new RoundedPanel(80);
        icono = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        nombrelogin = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(21, 69, 121));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cemail.setBackground(new java.awt.Color(255, 255, 255));
        cemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cemailActionPerformed(evt);
            }
        });
        jPanel1.add(cemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 440, 280, 40));

        Botonsiguiente.setBackground(new java.awt.Color(131, 150, 173));
        Botonsiguiente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Botonsiguiente.setForeground(new java.awt.Color(0, 0, 0));
        Botonsiguiente.setText("INGRESAR");
        Botonsiguiente.setBorder(null);
        Botonsiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Botonsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonsiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(Botonsiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 620, 230, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Usuario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 400, 100, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Contraseña:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 510, 140, -1));
        jPanel1.add(ccontrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 550, 280, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("REGISTRASTE");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 880, 170, 30));

        RegistrarseL.setBackground(null);
        RegistrarseL.setOpaque(false);
        RegistrarseL.setContentAreaFilled(false);
        RegistrarseL.setBorderPainted(false);
        RegistrarseL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RegistrarseL.setForeground(new java.awt.Color(0, 0, 0));
        RegistrarseL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton registrar.png"))); // NOI18N
        ImageIcon iconoOriginal = (ImageIcon) RegistrarseL.getIcon();
        Image imgOriginal = iconoOriginal.getImage();
        RegistrarseL.setBorderPainted(false);
        RegistrarseL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegistrarseL.setPreferredSize(new java.awt.Dimension(370, 120));
        RegistrarseL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarseLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegistrarseLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistrarseLMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RegistrarseLMouseReleased(evt);
            }
        });
        RegistrarseL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseLActionPerformed(evt);
            }
        });
        jPanel1.add(RegistrarseL, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 850, 290, 100));

        jLabel1.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¿Tienes cuenta?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 810, 230, -1));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 360, 340, 360));
        jPanel1.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 80, 80));
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 1350, 710));

        nombrelogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombrelogin.setForeground(new java.awt.Color(255, 255, 255));
        nombrelogin.setText("Login");
        jPanel1.add(nombrelogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 290, -1, -1));

        jButton1.setBackground(null);
        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pngegg.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 210, 60, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -240, 1410, 1010));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void SetImageLabel(JLabel fondo, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon =new ImageIcon(image.getImage().getScaledInstance(fondo.getWidth(),fondo.getHeight(), Image.SCALE_DEFAULT));
        fondo.setIcon(icon);
        this.repaint();

    }
        public class RoundedPanel extends JPanel {
    private int radius;

    public RoundedPanel(int radius) {
        this.radius = radius;
        setOpaque(false);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        int width = getWidth();
        int height = getHeight();
        Graphics2D graphics2D = (Graphics2D) g.create();

        graphics2D.setColor(getBackground());
        graphics2D.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        graphics2D.fillRoundRect(0, 0, width - 1, height - 1, radius, radius);

        graphics2D.dispose();
    }
}
    
    private void BotonsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonsiguienteActionPerformed

        String usuario = cemail.getText(); // 2
        String contrasena = String.valueOf(ccontrasena.getPassword());


       
       
        if (usuario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese su usuario", "Validación", JOptionPane.WARNING_MESSAGE);
            this.cemail.requestFocus();
            return;
        }else if (contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese contraseña", "Validación", JOptionPane.WARNING_MESSAGE);
            this.ccontrasena.requestFocus();
            return;
        }

        else{

            CuentaCON con = new CuentaCON();
            // Use the LoginCON class for database interaction
            int cod_cuenta = con.loginCuentax(usuario, contrasena);
            if (cod_cuenta!=-1) {
                this.dispose();
                Inicio ini = new Inicio(cod_cuenta);
                ini.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Usuario no existe o contraseña incorrecta", "Validación", JOptionPane.WARNING_MESSAGE);
                this.ccontrasena.requestFocus();
               
            
        
        }
}
        //boton siguiente:
    }//GEN-LAST:event_BotonsiguienteActionPerformed

    private void cemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cemailActionPerformed

    private void RegistrarseLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseLActionPerformed
        this.dispose();
        Registrar registrarse = new Registrar(); 
        registrarse.setVisible(true);
    }//GEN-LAST:event_RegistrarseLActionPerformed

    private void RegistrarseLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarseLMouseEntered
          Image imgOpaca = crearImagenOpaca(iconoOriginal.getImage()  , 0.7f); // Función para crear una imagen con opacidad
          RegistrarseL.setIcon(new ImageIcon(imgOpaca));
    }//GEN-LAST:event_RegistrarseLMouseEntered

    private void RegistrarseLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarseLMouseExited
          Image imgOpaca = crearImagenOpaca(iconoOriginal.getImage()  , 1.0f); // Función para crear una imagen con opacidad
          RegistrarseL.setIcon(new ImageIcon(imgOpaca));

    }//GEN-LAST:event_RegistrarseLMouseExited

    private void RegistrarseLMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarseLMouseReleased

    }//GEN-LAST:event_RegistrarseLMouseReleased

    private void RegistrarseLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarseLMouseClicked

    }//GEN-LAST:event_RegistrarseLMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botonsiguiente;
    private javax.swing.JButton RegistrarseL;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPasswordField ccontrasena;
    private javax.swing.JTextField cemail;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel icono;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nombrelogin;
    // End of variables declaration//GEN-END:variables

private Image crearImagenOpaca(Image img, float opacidad) {
    BufferedImage imagenOpaca = new BufferedImage(img.getWidth(null), img.getHeight(null), BufferedImage.TYPE_INT_ARGB);
    Graphics2D g2 = imagenOpaca.createGraphics();
    g2.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, opacidad));
    g2.drawImage(img, 0, 0, null);
    g2.dispose();
    return imagenOpaca;
}
}
