/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.CuentaCON;
import Modelo.Cuenta;
import java.util.Date;
import javax.swing.JTextField;
import com.toedter.calendar.JDateChooser;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gauge
 */
public class Registrar extends javax.swing.JFrame {
   
  
 //   Registrar2 v2 = new Registrar2(); //inicializa registro 2 para usar más tarde
    String run;
//    Login loginN = new Login();
    public Registrar() {
        
        initComponents();
        this.setLocationRelativeTo(this);
        SetImageLabel(fondo, "src/imagenes/fondo.png");
        SetImageLabel(icono, "src/imagenes/icono.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    

    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        cnombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        capellido = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Botonsiguiente = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ccontrasena1 = new javax.swing.JPasswordField();
        ccontrasena2 = new javax.swing.JPasswordField();
        icono = new javax.swing.JLabel();
        jPanel2 = new RoundedPanel(80);
        fondo = new javax.swing.JLabel();
        nombrelogin = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(21, 69, 121));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cnombre.setBackground(new java.awt.Color(255, 255, 255));
        cnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnombreActionPerformed(evt);
            }
        });
        jPanel1.add(cnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 480, 280, 40));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("E-mail:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 620, 90, -1));

        capellido.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(capellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 570, 280, 35));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Confirmar contraseña: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 780, 210, -1));

        Botonsiguiente.setBackground(new java.awt.Color(0, 0, 0));
        Botonsiguiente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Botonsiguiente.setForeground(new java.awt.Color(255, 255, 255));
        Botonsiguiente.setText("REGISTRASE");
        Botonsiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Botonsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonsiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(Botonsiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 870, 230, 40));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("¡Registrate Ahora! ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 310, 330, 60));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombres:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 450, 110, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Apellidos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 540, 110, -1));

        cmail.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(cmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 650, 280, 35));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Contraseña:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 700, 130, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Datos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 390, -1, -1));
        jPanel1.add(ccontrasena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 730, 280, 40));
        jPanel1.add(ccontrasena2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 810, 280, 40));
        jPanel1.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 80, 80));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 380, 340, 610));
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 1350, 710));

        nombrelogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombrelogin.setForeground(new java.awt.Color(255, 255, 255));
        nombrelogin.setText("Login");
        jPanel1.add(nombrelogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 290, -1, -1));

        jButton1.setBackground(null);
        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pngegg.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 210, 60, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -240, 1410, 1010));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void SetImageLabel(JLabel fondo, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon =new ImageIcon(image.getImage().getScaledInstance(fondo.getWidth(),fondo.getHeight(), Image.SCALE_DEFAULT));
        fondo.setIcon(icon);
        this.repaint();
        
    }
    public class RoundedPanel extends JPanel {
    private int radius;

    public RoundedPanel(int radius) {
        this.radius = radius;
        setOpaque(false);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        int width = getWidth();
        int height = getHeight();
        Graphics2D graphics2D = (Graphics2D) g.create();

        graphics2D.setColor(getBackground());
        graphics2D.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        graphics2D.fillRoundRect(0, 0, width - 1, height - 1, radius, radius);

        graphics2D.dispose();
    }
}

    
    private void BotonsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonsiguienteActionPerformed
        Cuenta cuenta = new Cuenta();
        String name = cnombre.getText(); // 2
        String apellido = capellido.getText();
        String email = cmail.getText();
        String contrasena1 = String.valueOf(ccontrasena1.getPassword());
        String contrasena2 = String.valueOf(ccontrasena2.getPassword());
        int emaillargo = email.length();

      
       
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese nombre", "Validación", JOptionPane.WARNING_MESSAGE);
            this.cnombre.requestFocus();
            return;
        }else if (apellido.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese apellidos", "Validación", JOptionPane.WARNING_MESSAGE);
            this.capellido.requestFocus();
            return;
        }else if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese email", "Validación", JOptionPane.WARNING_MESSAGE);
            this.cmail.requestFocus();
            return;
        }else if (contrasena1.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese contraseña", "Validación", JOptionPane.WARNING_MESSAGE);
            this.ccontrasena1.requestFocus();
            return;
        }else if (contrasena2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese contraseña comprobación", "Validación", JOptionPane.WARNING_MESSAGE);
            this.ccontrasena2.requestFocus();
            return;
        }else if (!contrasena1.equalsIgnoreCase(contrasena2)) {
            JOptionPane.showMessageDialog(this, "contraseña distintas, intente nuevamente", "Validación", JOptionPane.WARNING_MESSAGE);
            this.ccontrasena1.requestFocus();
            return;
        }else if (!contrasena1.equalsIgnoreCase(contrasena2)) {
            JOptionPane.showMessageDialog(this, "contraseña distintas, intente nuevamente", "Validación", JOptionPane.WARNING_MESSAGE);
            this.ccontrasena1.requestFocus();
            return;
        }else if (emaillargo<12 || !email.endsWith("@duocuc.cl")) {
            JOptionPane.showMessageDialog(this, "correo invalido, intente nuevamente", "Validación", JOptionPane.WARNING_MESSAGE);
            this.cmail.requestFocus();
            return;
        }
        
        
        else{
            
            CuentaCON reg = new CuentaCON();
            cuenta.setCuenta(email);
            cuenta.setNombre(name);
            cuenta.setApellidos(apellido);
            cuenta.setContrasena(contrasena1);
 
            try {
                if (reg.agregarCuenta(cuenta)) {
                    JOptionPane.showMessageDialog(this, "Cuenta creada exitosamente", "Información", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    Login loginN = new Login();
                    loginN.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Problemas, intente más tarde", "Validación", JOptionPane.WARNING_MESSAGE);
                    this.cmail.requestFocus();
                }
            } catch (Exception ex) {
                Logger.getLogger(Registrar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //boton siguiente:
    }//GEN-LAST:event_BotonsiguienteActionPerformed

    private void cnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         this.dispose();
         Login loginN = new Login();
        loginN.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
                new Registrar().setVisible(true);
            }
        });
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botonsiguiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField capellido;
    private javax.swing.JPasswordField ccontrasena1;
    private javax.swing.JPasswordField ccontrasena2;
    private javax.swing.JTextField cmail;
    private javax.swing.JTextField cnombre;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel icono;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nombrelogin;
    // End of variables declaration//GEN-END:variables
}
